mysite/confirm/urls.py
from django.urls import path
from . import views

app_name = "conf" # HTMLで参照するときに名前空間で識別
urlpatterns = [
    path("", views.index, name="index"),
    path("inquiry1", views.Inquiry1View.as_view(), name="inquiry1"),
    path("inquiry2", views.Inquiry2View.as_view(), name="inquiry2"),
    path("confirm1", views.Confirm1View.as_view(), name="confirm1"),
    path("complete", views.CompleteView.as_view(), name="complete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("polls2/", include("polls2.urls")),
    path("fv/", include("formview_sample.urls")),
    path("form_tag/", include("form_tag.urls")),
    path("register/", include("register.urls")),
    path("add_attr/", include("add_attr.urls")),
    path("valid_post/", include("valid_post.urls")),
    path("confirm/", include("confirm.urls")),

    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls" # HTMLで参照するときに名前空間で識別
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/index02/
    path("index02/", views.index02, name="index02"),
    path("index03/", views.index03, name="index03"),
    path("index04/", views.index04, name="index04"),
    # ex: /polls/dummy5/
    path("dummy<int:question_id>/", views.detail_dummy, name="detail_dummy"),
    # ex: /polls/detail5/
    path("detail<int:question_id>/", views.detail_long, name="detail_long"),

    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/confirm/models.py
from django.db import models

# Create your models here.

mysite/confirm/forms.py
from django import forms


class Inquiry1Form(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        print("送信", subject, message)


class Inquiry2Form(Inquiry1Form):
    ex_info = forms.CharField(label='追加情報', max_length=30)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class Confirm1Form(Inquiry2Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class CompleteForm(Confirm1Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

mysite/confirm/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from .forms import Confirm1Form, Inquiry1Form, CompleteForm, Inquiry2Form

# Create your views here.
def index(request):
    return HttpResponse("<h1>Hello, world. confirm</h1>")


# class UserList(generic.ListView):
#     template_name = 'register/user_list.html'  # デフォルトUserだと、authアプリケーションのuser_list.htmlを探すため、明示的に書いておく
#     model = User


class Inquiry1View(generic.FormView):
    """ユーザー情報の入力

    このビューが呼ばれるのは、以下の2箇所です。
    ・初回の入力欄表示(aタグでの遷移)
    ・確認画面から戻るを押した場合(これはPOSTで飛んできます)

    初回の入力欄表示の際は、空のフォームをuser_data_input.htmlに渡し、
    戻る場合は、POSTで飛んできたフォームデータをそのままuser_data_input.htmlに渡します。
    """
    template_name = 'confirm/inquiry1.html'
    form_class = Inquiry1Form

    # 次の画面から戻るときに走る
    def form_valid(self, form):
        print(self.__class__.__name__, "form valid")
        print(form)
        return render(self.request, self.template_name, {'form': form})


class Inquiry2View(generic.FormView):
    template_name = 'confirm/inquiry2.html'
    prev_template_name = 'confirm/inquiry1.html'
    
    form_class = Inquiry2Form

    # 次の画面から戻るときに走る
    def form_valid(self, form):
        print(self.__class__.__name__, "form valid")
        return render(self.request, self.template_name, {'form': form})


class Confirm1View(generic.FormView):
    """ユーザー情報の確認

    ユーザー情報入力後、「送信」を押すとこのビューが呼ばれます。(user_data_input.htmlのform action属性がこのビュー)
    データが問題なければuser_data_confirm.html(確認ページ)を、入力内容に不備があればuser_data_input.html(入力ページ)に
    フォームデータを渡します。

    """
    form_class = Confirm1Form
    template_name = "confirm/confirm1.html"
    prev_template_name = 'confirm/inquiry2.html'

    def form_valid(self, form):
        print(self.__class__.__name__, "form valid")
        return render(self.request, self.template_name, {'form': form})

    # https://yu-nix.com/archives/django-form-validation/
    def form_invalid(self, form):
        print(self.__class__.__name__, "form invalid")
        return render(self.request, self.prev_template_name, {'form': form})
    
    # 画面遷移で無く直接URL叩いたときにくる
    # 不正なので，エラーにすべき？
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        print(self.__class__.__name__, "get")
        return super().get(request, *args, **kwargs)


class CompleteView(generic.FormView):
    form_class = CompleteForm
    template_name = "confirm/complete.html"
    prev_template_name = 'confirm/confirm1.html'

    def form_valid(self, form):
        print(self.__class__.__name__, "form valid")
        return render(self.request, self.template_name, {'form': form})

    def form_invalid(self, form):
        print(self.__class__.__name__, "form invalid")
        return render(self.request, self.prev_template_name, {'form': form})


# class UserDataCreate(generic.CreateView):
#     """ユーザーデータの登録ビュー。ここ以外では、CreateViewを使わないでください"""
#     form_class = UserCreateForm
#     success_url = reverse_lazy('register:user_list')

#     def form_invalid(self, form):
#         """基本的にはここに飛んでこないはずです。UserDataConfrimでバリデーションは済んでるため"""
#         return render(self.request, 'register/user_data_input.html', {'form': form})

mysite/confirm/templates/confirm/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>confirmテスト</title>
</head>
<body>

    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

mysite/confirm/templates/confirm/complete.html
{% extends "register/base.html" %}
{% block content %}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
    </div>
    {% endfor %}

    <form action="{% url 'conf:confirm1' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    {% comment %} <hr>
    <form action="{% url 'conf:complete' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form> {% endcomment %}
{% endblock %}

mysite/confirm/templates/confirm/confirm1.html
{% extends "register/base.html" %}
{% block content %}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
        {{ field.errors }}
    </div>
    {% endfor %}

    <form action="{% url 'conf:inquiry2' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    <hr>
    <form action="{% url 'conf:complete' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
{% endblock %}

mysite/confirm/templates/confirm/inquiry1.html
{% extends "register/base.html" %}
{% block content %}
<form action="{% url 'conf:inquiry2' %}" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">次へ</button>
</form>
{% endblock %}

mysite/confirm/templates/confirm/inquiry2.html
{% extends "register/base.html" %}
{% block content %}
    {{ form.non_field_errors }}

    {{ form.ex_info }}
    {{ form.ex_info.errors }}

    {% comment %} {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %} {% endcomment %}
    {% csrf_token %}
    <form action="{% url 'conf:inquiry1' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    <hr>
    <form action="{% url 'conf:confirm1' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
{% endblock %}