mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("polls2/", include("polls2.urls")),
    path("fv/", include("formview_sample.urls")),
    path("form_tag/", include("form_tag.urls")),
    path("register/", include("register.urls")),
    path("add_attr/", include("add_attr.urls")),
    path("valid_post/", include("valid_post.urls")),
    path("confirm/", include("confirm.urls")),

    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls" # HTMLで参照するときに名前空間で識別
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/index02/
    path("index02/", views.index02, name="index02"),
    path("index03/", views.index03, name="index03"),
    path("index04/", views.index04, name="index04"),
    # ex: /polls/dummy5/
    path("dummy<int:question_id>/", views.detail_dummy, name="detail_dummy"),
    # ex: /polls/detail5/
    path("detail<int:question_id>/", views.detail_long, name="detail_long"),

    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/polls2/urls.py
from django.urls import path
from . import views

app_name = "polls2" # HTMLで参照するときに名前空間で識別
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/polls2/models.py
import datetime
from django.db import models
from django.utils import timezone


# question.choice_set.all のようにQuestionからChoiceのリストを取得できる
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    # 任意の関数を追加
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls2/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls2/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls2/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls2/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        # request.POST で送信したデータを取得できる
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls2/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls2:results", args=(question.id,)))

mysite/polls2/templates/polls2/detail.html
<form action="{% url 'polls2:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

mysite/polls2/templates/polls2/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% comment %} 別のURLへ飛ばす {% endcomment %}
        <li><a href="/polls2/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% comment %} 上記のハードコーディングからpathのnameを参照する方式に修正 {% endcomment %}
        <li><a href="{% url 'polls2:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls2/templates/polls2/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls2:detail' question.id %}">Vote again?</a>