mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("polls2/", include("polls2.urls")),
    path("fv/", include("formview_sample.urls")),
    path("form_tag/", include("form_tag.urls")),
    path("register/", include("register.urls")),
    path("add_attr/", include("add_attr.urls")),
    path("valid_post/", include("valid_post.urls")),
    path("confirm/", include("confirm.urls")),

    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls" # HTMLで参照するときに名前空間で識別
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/index02/
    path("index02/", views.index02, name="index02"),
    path("index03/", views.index03, name="index03"),
    path("index04/", views.index04, name="index04"),
    # ex: /polls/dummy5/
    path("dummy<int:question_id>/", views.detail_dummy, name="detail_dummy"),
    # ex: /polls/detail5/
    path("detail<int:question_id>/", views.detail_long, name="detail_long"),

    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/register/urls.py
# https://blog.narito.ninja/detail/45
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.UserList.as_view(), name='user_list'),
    path('user_data_input/', views.UserDataInput.as_view(), name='user_data_input'),
    path('user_data_confirm/', views.UserDataConfirm.as_view(), name='user_data_confirm'),
    path('user_data_create/', views.UserDataCreate.as_view(), name='user_data_create'),
]

mysite/register/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()  # Userモデルの柔軟な取得方法


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = (User.USERNAME_FIELD,)  # ユーザー名として扱っているフィールドだけ、作成時に入力する

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

mysite/register/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import UserCreateForm

User = get_user_model()


class UserList(generic.ListView):
    template_name = 'register/user_list.html'  # デフォルトUserだと、authアプリケーションのuser_list.htmlを探すため、明示的に書いておく
    model = User


class UserDataInput(generic.FormView):
    """ユーザー情報の入力

    このビューが呼ばれるのは、以下の2箇所です。
    ・初回の入力欄表示(aタグでの遷移)
    ・確認画面から戻るを押した場合(これはPOSTで飛んできます)

    初回の入力欄表示の際は、空のフォームをuser_data_input.htmlに渡し、
    戻る場合は、POSTで飛んできたフォームデータをそのままuser_data_input.htmlに渡します。

    """
    template_name = 'register/user_data_input.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        return render(self.request, 'register/user_data_input.html', {'form': form})


class UserDataConfirm(generic.FormView):
    """ユーザー情報の確認

    ユーザー情報入力後、「送信」を押すとこのビューが呼ばれます。(user_data_input.htmlのform action属性がこのビュー)
    データが問題なければuser_data_confirm.html(確認ページ)を、入力内容に不備があればuser_data_input.html(入力ページ)に
    フォームデータを渡します。

    """
    form_class = UserCreateForm

    def form_valid(self, form):
        return render(self.request, 'register/user_data_confirm.html', {'form': form})

    def form_invalid(self, form):
        return render(self.request, 'register/user_data_input.html', {'form': form})


class UserDataCreate(generic.CreateView):
    """ユーザーデータの登録ビュー。ここ以外では、CreateViewを使わないでください"""
    form_class = UserCreateForm
    success_url = reverse_lazy('register:user_list')

    def form_invalid(self, form):
        """基本的にはここに飛んでこないはずです。UserDataConfrimでバリデーションは済んでるため"""
        return render(self.request, 'register/user_data_input.html', {'form': form})

mysite/register/templates/register/user_data_confirm.html
{% extends "register/base.html" %}
{% block content %}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
    </div>
    {% endfor %}

    <form action="{% url 'register:user_data_input' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    <hr>
    <form action="{% url 'register:user_data_create' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
{% endblock %}

mysite/register/templates/register/user_data_input.html
{% extends "register/base.html" %}
{% block content %}
<form action="{% url 'register:user_data_confirm' %}" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

mysite/register/templates/register/user_list.html
{% extends "register/base.html" %}
{% block content %}
<p><a href="{% url 'register:user_data_input' %}">ユーザー作成</a></p><hr>
{% for user in user_list %}
    <p>ユーザー名: {{ user.username }}</p><hr>
{% endfor %}
{% endblock %}