mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("polls2/", include("polls2.urls")),
    path("fv/", include("formview_sample.urls")),
    path("form_tag/", include("form_tag.urls")),
    path("register/", include("register.urls")),
    path("add_attr/", include("add_attr.urls")),
    path("valid_post/", include("valid_post.urls")),
    path("confirm/", include("confirm.urls")),

    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls" # HTMLで参照するときに名前空間で識別
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/index02/
    path("index02/", views.index02, name="index02"),
    path("index03/", views.index03, name="index03"),
    path("index04/", views.index04, name="index04"),
    # ex: /polls/dummy5/
    path("dummy<int:question_id>/", views.detail_dummy, name="detail_dummy"),
    # ex: /polls/detail5/
    path("detail<int:question_id>/", views.detail_long, name="detail_long"),

    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/valid_post/urls.py
# https://blog.narito.ninja/detail/45
from django.urls import path
from . import views

app_name = 'valid_post'

urlpatterns = [
    path('', views.UserList.as_view(), name='user_list'),
    path('user_data_input/', views.UserDataInput.as_view(), name='user_data_input'),
    path('user_data_confirm/', views.UserDataConfirm.as_view(), name='user_data_confirm'),
    path('user_data_create/', views.UserDataCreate.as_view(), name='user_data_create'),
]

mysite/valid_post/forms.py
from django import forms


class UserCreateForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    choice_dict = (
        ("1", "hoge"),
        ("2", "foo"),
    )
    choice = forms.ChoiceField(choices=choice_dict)
    user_id = forms.CharField(initial="1234")

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'my-class my-class2'
            field.widget.attrs['foo'] = '3'
        self.fields['name'].widget.attrs['name-attr'] = '1'

mysite/valid_post/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import UserCreateForm

class UserList(generic.ListView):
    template_name = 'valid_post/user_list.html'  # デフォルトUserだと、authアプリケーションのuser_list.htmlを探すため、明示的に書いておく

class UserDataInput(generic.FormView):
    template_name = 'valid_post/user_data_input.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        return render(self.request, 'valid_post/user_data_input.html', {'form': form})


class UserDataConfirm(generic.FormView):
    form_class = UserCreateForm

    def post(self, request, *args, **kwargs):
        print("post-------------")
        context = self.get_context_data(**kwargs)
        form = context["form"]  # contextはformとviweのオブジェクトをdictで持っている
        print(form.data.dict()["name"])  # validが評価されていないため，cleaned_dataはまだ使えない
        if form.is_valid():
            print(form.cleaned_data["name"])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):  # formにはform_classで指定した型のオブジェクトが入る
        print("form_valid-------------")
        name = form.cleaned_data["name"]  # 辞書型でデータにアクセスできる
        print("form.cleaned_data", form.cleaned_data)
        print("form.data.dict()", form.data.dict())
        non_form_text = form.data.dict()["non_form_text"]  # form_classにない要素はこっちで取得する

        return render(self.request, 'valid_post/user_data_confirm.html', {'form': form})

    def form_invalid(self, form):
        return render(self.request, 'valid_post/user_data_input.html', {'form': form})


class UserDataCreate(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('valid_post:user_list')

    def form_invalid(self, form):
        return render(self.request, 'valid_post/user_data_input.html', {'form': form})

mysite/valid_post/templates/valid_post/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>会員登録サンプル</title>
</head>
<body>

    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

mysite/valid_post/templates/valid_post/user_data_confirm.html
{% extends "valid_post/base.html" %}
{% block content %}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field.value }}
    </div>
    {% endfor %}

    <form action="{% url 'valid_post:user_data_input' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    <hr>
    <form action="{% url 'valid_post:user_data_create' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
{% endblock %}

mysite/valid_post/templates/valid_post/user_data_input.html
{% extends "valid_post/base.html" %}
{% block content %}
<form action="{% url 'valid_post:user_data_confirm' %}" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        {% if field.name == "user_id" %}
            {% comment %} 特定のformを隠したい場合 {% endcomment %}
            {{ field.as_hidden }}
        {% else %}
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        {% endif %}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
    <input type="text" name="non_form_text" id="non_form_text_id">
</form>
{% endblock %}

mysite/valid_post/templates/valid_post/user_list.html
{% extends "valid_post/base.html" %}
{% block content %}
<p><a href="{% url 'valid_post:user_data_input' %}">ユーザー作成</a></p><hr>
{% for user in user_list %}
    <p>ユーザー名: {{ user.username }}</p><hr>
{% endfor %}
{% endblock %}